/EkfCalNode:
    ros__parameters:
        debug_log_level: 2
        data_logging_on: true
        body_data_rate: 10.0
        process_noise:
            pos: 1.0e-3
            vel: 1.0e-4
            acc: 1.0e-1
            ang_pos: 1.0e-3
            ang_vel: 1.0e-1
            ang_acc: 1.0e-5
        sim_params:
            seed: 0.0
            use_seed: true
            max_time: 60.0
            no_errors: false
            number_of_runs: 10
            run_number: 0
            truth_type: "cyclic"
            stationary_time: 5.0
            pos_frequency: [0.3, 0.5, 0.7]
            ang_frequency: [0.3, 0.4, 0.5]
            pos_offset: [0.0, 0.0, 0.0]
            ang_offset: [0.0, 0.0, 0.0]
            ang_amplitude: 0.1
            pos_amplitude: 1.0

        imu_list:
            - "imu_1"

        camera_list:
            - "cam_1"

        tracker_list: []

        fiducial_list:
            - "charuco"

        gps_list: []

        imu:
            imu_1:
                use_for_prediction: true
                is_extrinsic: false
                is_intrinsic: false
                rate: 400.0
                topic: "/imu_1"
                variance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
                pos_i_in_b: [0.0, 0.0, 0.0]
                ang_i_to_b: [1.0, 0.0, 0.0, 0.0]
                acc_bias: [0.0, 0.0, 0.0]
                omg_bias: [0.0, 0.0, 0.0]
                pos_stability: 1.0e-2
                ang_stability: 1.0e-2
                acc_bias_stability: 1.0e-3
                omg_bias_stability: 1.0e-3
                data_log_rate: 5.0
                sim_params:
                    time_bias_error: 1.0e-9
                    time_error: 1.0e-9
                    pos_error: [0.0, 0.0, 0.0]
                    ang_error: [0.0, 0.0, 0.0]
                    acc_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    omg_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    acc_bias_error: [1.0e-1, 1.0e-1, 1.0e-1]
                    omg_bias_error: [1.0e-1, 1.0e-1, 1.0e-1]

        camera:
            cam_1:
                rate: 20.0
                topic:  "/cam_1"
                pos_c_in_b: [0.0, 0.0, 0.0]
                ang_c_to_b: [-0.5, 0.5, -0.5, 0.5]
                variance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
                fiducial: "charuco"
                pos_stability: 1.0e-9
                ang_stability: 1.0e-9
                intrinsics:
                    F: 0.01
                    c_x: 320.0
                    c_y: 240.0
                    k_1: 0.0
                    k_2: 0.0
                    p_1: 0.0
                    p_2: 0.0
                    pixel_size: 5.0e-6
                sim_params:
                    time_bias_error: 1.0e-9
                    time_error: 1.0e-9
                    pos_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    ang_error: [1.0e-2, 1.0e-2, 1.0e-2]

        fiducial:
            charuco:
                fiducial_type: 1
                squares_x: 5
                squares_y: 7
                square_length: 0.04
                marker_length: 0.02
                pos_f_in_l: [5.0, 0.0, 0.0]
                ang_f_to_l: [1.0, 0.0, 0.0, 0.0]
                variance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
                min_track_length: 0
                max_track_length: 1
                data_log_rate: 10.0
                sim_params:
                    pos_error: [1.0e-1, 1.0e-1, 1.0e-1]
                    ang_error: [1.0e-1, 1.0e-1, 1.0e-1]
                    t_vec_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    r_vec_error: [1.0e-2, 1.0e-2, 1.0e-2]

        tracker: {}

        gps: {}
