/EkfCalNode:
    ros__parameters:
        debug_log_level: 2
        data_log_rate: 20.0
        process_noise:
            pos: 1.0e-0
            vel: 1.0e-1
            acc: 1.0e-2
            ang_pos: 1.0e-0
            ang_vel: 1.0e-1
            ang_acc: 1.0e-2
        sim_params:
            seed: 1
            max_time: 300.0
            number_of_runs: 10
            run_number: 0
            truth_type: "cyclic"
            stationary_time: 0.1
            pos_frequency: [0.3, 0.5, 0.7]
            ang_frequency: [0.3, 0.4, 0.5]
            pos_offset: [0.0, 0.0, 0.0]
            ang_offset: [0.0, 0.0, 0.0]
            ang_amplitude: 1.5
            pos_amplitude: 1.5

        imu_list:
            - "imu_1"

        camera_list:
            - "cam_1"

        tracker_list: []

        fiducial_list:
            - "charuco"

        gps_list: []

        imu:
            imu_1:
                is_extrinsic: false
                is_intrinsic: false
                rate: 400.0
                topic: "/imu_1"
                variance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
                pos_i_in_b: [0.0, 0.0, 0.0]
                ang_i_to_b: [1.0, 0.0, 0.0, 0.0]
                acc_bias: [0.0, 0.0, 0.0]
                omg_bias: [0.0, 0.0, 0.0]
                data_log_rate: 20.0
                sim_params:
                    acc_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    omg_error: [1.0e-2, 1.0e-2, 1.0e-2]

        camera:
            cam_1:
                rate: 20.0
                topic:  "/cam_1"
                pos_c_in_b: [1.0, 0.5, -1.5]
                ang_c_to_b: [-0.5, 0.5, -0.5, 0.5]
                variance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
                fiducial: "charuco"
                pos_stability: 1.0e-4
                ang_stability: 1.0e-4
                data_log_rate: 20.0
                is_extrinsic: true
                sim_params:
                    pos_error: [0.1, 0.1, 0.1]
                    ang_error: [0.1, 0.1, 0.1]

        fiducial:
            charuco:
                fiducial_type: 1
                squares_x: 5
                squares_y: 7
                square_length: 0.04
                marker_length: 0.02
                pos_f_in_l: [0.0, 0.0, 0.0]
                ang_f_to_l: [1.0, 0.0, 0.0, 0.0]
                variance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
                is_extrinsic: false
                sim_params:
                    t_vec_error: [1.0e-1, 1.0e-1, 1.0e-1]
                    r_vec_error: [1.0e-2, 1.0e-2, 1.0e-2]

        tracker: {}

        gps: {}
