/EkfCalNode:
    ros__parameters:
        debug_log_level: 2
        data_log_rate: 1.0
        process_noise:
            pos: 1.0e-6
            vel: 5.0e-6
            ang_pos: 1.0e-1

        gps_init_type: 0
        gps_init_pos_thresh: 0.1
        gps_init_ang_thresh: 0.1
        gps_init_baseline_dist: 100.0

        sim_params:
            seed: 1.0
            max_time: 300.0
            number_of_runs: 10
            run_number: 0
            stationary_time: 500.0
            truth_type: "spline"
            positions: [
                00.0, 00.0, 00.0,
                10.0, 05.0, 10.0,
                20.0, 20.0, 25.0,
                35.0, 30.0, 30.0,
                40.0, 40.0, 40.0
            ]
            angles: [
                0.0, 0.0, 0.0,
                0.5, 0.0, 0.0,
                0.0, 0.5, 0.0,
                0.0, 0.0, 0.5,
                0.0, 0.0, 0.0
            ]
            pos_e_in_g: [1.0e-9, 1.0e-9, 1.0e-9]
            ang_l_to_e: 1.0e-9
            pos_e_in_g_error: [1.0e-9, 1.0e-9, 1.0e-9]
            ang_l_to_e_error: 1.0e-9
            pos_b_in_l_error: [1.0e-9, 1.0e-9, 1.0e-9]
            ang_b_to_l_error: [1.0e-9, 1.0e-9, 1.0e-9]

        imu_list:
            - "imu_1"

        camera_list: []

        tracker_list: []

        fiducial_list: []

        gps_list:
            - "gps_1"

        imu:
            imu_1:
                is_extrinsic: false
                is_intrinsic: false
                rate: 400.0
                topic: "/imu_1"
                variance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
                pos_i_in_b: [0.0, 0.0, 0.0]
                ang_i_to_b: [1.0, 0.0, 0.0, 0.0]
                acc_bias: [0.0, 0.0, 0.0]
                omg_bias: [0.0, 0.0, 0.0]
                pos_stability: 1.0e-2
                ang_stability: 1.0e-2
                data_log_rate: 1.0
                use_for_prediction: true
                sim_params:
                    pos_error: [0.0, 0.0, 0.0]
                    ang_error: [0.0, 0.0, 0.0]
                    acc_error: [1.0e-6, 1.0e-6, 1.0e-6]
                    omg_error: [1.0e-6, 1.0e-6, 1.0e-6]

        camera: {}

        tracker: {}

        fiducial: {}

        gps:
            gps_1:
                rate: 10.0
                topic: "/gps1"
                pos_a_in_b: [0.0, 0.0, 0.0]
                variance: [1.0, 1.0, 1.0]
                data_log_rate: 1.0
                pos_stability: 1.0e-4
                is_extrinsic: true
                sim_params:
                    lla_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    pos_a_in_b_err: [1.0e-0, 1.0e-0, 1.0e-0]
