/EkfCalNode:
    ros__parameters:
        debug_log_level: 2
        data_logging_on: true
        data_log_rate: 10.0
        process_noise:
            pos: 1.0e-3
            vel: 5.0e-1
            ang_pos: 1.0e-1
        sim_params:
            seed: 0.0
            use_seed: true
            max_time: 6.0
            number_of_runs: 10
            run_number: 0
            stationary_time: 1.0
            truth_type: "spline"
            positions:
                - [00.0, 00.0, 00.0]
                - [10.0, 05.0, 10.0]
                - [20.0, 20.0, 25.0]
                - [35.0, 30.0, 30.0]
                - [40.0, 40.0, 40.0]
            angles:
                - [0.0, 0.0, 0.0]
                - [0.5, 0.0, 0.0]
                - [0.0, 0.5, 0.0]
                - [0.0, 0.0, 0.5]
                - [0.0, 0.0, 0.0]
            pos_l_in_g: [0.0, 0.0, 0.0]
            ang_l_to_g: 0.0
            pos_l_in_g_error: [1.0e-9, 1.0e-9, 1.0e-9]
            ang_l_to_g_error: 1.0e-9
            pos_b_in_l_error: [0.0, 0.0, 0.0]
            ang_b_to_l_error: [0.5, 0.5, 0.5]

        imu_list:
            - "imu_1"

        camera_list: []

        tracker_list: []

        fiducial_list: []

        gps_list:
            - "gps_1"

        imu:
            imu_1:
                is_extrinsic: false
                is_intrinsic: false
                rate: 40.0
                topic: "/imu_1"
                variance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
                pos_i_in_b: [0.0, 0.0, 0.0]
                ang_i_to_b: [1.0, 0.0, 0.0, 0.0]
                acc_bias: [0.0, 0.0, 0.0]
                omg_bias: [0.0, 0.0, 0.0]
                pos_stability: 1.0e-2
                ang_stability: 1.0e-2
                acc_bias_stability: 1.0e-3
                omg_bias_stability: 1.0e-3
                data_log_rate: 10.0
                sim_params:
                    time_bias_error: 1.0e-9
                    time_error: 1.0e-6
                    pos_error: [0.0, 0.0, 0.0]
                    ang_error: [0.0, 0.0, 0.0]
                    acc_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    omg_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    acc_bias_error: [0.0, 0.0, 0.0]
                    omg_bias_error: [0.0, 0.0, 0.0]

        camera: {}

        tracker: {}

        fiducial: {}

        gps:
            gps_1:
                rate: 10.0
                topic: "/gps1"
                pos_a_in_b: [0.0, 0.0, 0.0]
                variance: [1.0, 1.0, 1.0]
                data_log_rate: 10.0
                initialization_type: 0
                init_pos_thresh: 0.1
                init_ang_thresh: 0.1
                init_baseline_dist: 100.0
                pos_stability: 1.0e-9
                is_extrinsic: true
                sim_params:
                    no_errors: false
                    time_bias_error: 1.0e-9
                    time_error: 1.0e-9
                    lla_error: [1.0, 1.0, 1.0]
                    pos_a_in_b_err: [1.0e-1, 1.0e-1, 1.0e-1]
