
/EkfCalNode:
    ros__parameters:
        debug_log_level: 2
        data_logging_on: True
        body_data_rate: 10.0
        process_noise: [
            1.0e-3, 1.0e-3, 1.0e-3,
            1.0e-4, 1.0e-4, 1.0e-4,
            1.0e-5, 1.0e-5, 1.0e-5,
            1.0e-3, 1.0e-3, 1.0e-3,
            1.0e-4, 1.0e-4, 1.0e-4,
            1.0e-5, 1.0e-5, 1.0e-5,
        ]
        sim_params:
            seed: 0.0
            use_seed: True
            max_time: 60.0
            truth_type: "cyclic"
            pos_frequency: [0.3, 0.5, 0.7]
            ang_frequency: [0.0, 0.0, 0.0]
            pos_offset: [0.0, 0.0, 0.0]
            no_errors: False
            number_of_runs: 10
            run_number: 0

        imu_list:
            - "vn300"

        camera_list:

        tracker_list:

        imu:
            vn300:
                use_for_prediction: False
                is_extrinsic: false
                is_intrinsic: False
                rate: 4000.0
                topic: "/vn300/imu_uncompensated"
                variance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
                pos_i_in_b: [0.0, 0.0, 0.0]
                ang_i_to_b: [1.0, 0.0, 0.0, 0.0]
                acc_bias: [0.0, 0.0, 0.0]
                omg_bias: [0.0, 0.0, 0.0]
                sim_params:
                    time_bias_error: 0.0
                    time_error: 1.0e-6
                    acc_bias_error: [1.0e-3, 1.0e-3, 1.0e-3]
                    omg_bias_error: [1.0e-2, 1.0e-2, 1.0e-2]
                    pos_error: [0.0, 0.0, 0.0]
                    ang_error: [0.0, 0.0, 0.0]